# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=250)),
                ('port', models.CharField(max_length=4)),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
    ]
